/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.main;

import java.io.IOException;
import java.nio.file.Paths;
import static java.nio.file.StandardWatchEventKinds.ENTRY_CREATE;
import static java.nio.file.StandardWatchEventKinds.ENTRY_DELETE;
import static java.nio.file.StandardWatchEventKinds.ENTRY_MODIFY;
import java.nio.file.WatchEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.vns.common.files.DefaultWatchRegistry;
import org.vns.common.files.FileChangeAdapter;
import org.vns.common.files.FileEvent;
import org.vns.common.files.FilePathObject;

/**
 *
 * @author Valery
 */
public class ChainFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChainFrame
     */
    public ChainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createRegistryForDButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createRegistryForDButton.setText("Create Registry for D");
        createRegistryForDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRegistryForDButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createRegistryForDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(createRegistryForDButton)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultWatchRegistry mainRegistry;
    FileChangeAdapter mainAdapter;
    
    FilePathObject poD;
    
    FileChangeAdapter createAdapter() {
        FileChangeAdapter adapter = new FileChangeAdapter() {
            @Override
            public void fileCreated(FileEvent ev) {
                setResult("FILE_ENTRY_CREATE");
                System.out.println("RESULT:" + getResult());

            }

            @Override
            public void fileDeleted(FileEvent ev) {
                setResult("FILE_ENTRY_DELETE");
                System.out.println("RESULT:" + getResult());

            }

            @Override
            public void folderCreated(FileEvent ev) {
                setResult("FOLDER_ENTRY_CREATE");
                System.out.println("RESULT:" + getResult());

            }

            @Override
            public void folderDeleted(FileEvent ev) {

                setResult("FOLDER_ENTRY_DELETE");
                System.out.println("RESULT:" + getResult());
            }

        };
        return adapter;
    }
  
    private void createRegistryForDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRegistryForDButtonActionPerformed
        try {
            mainRegistry = new DefaultWatchRegistry();
            mainRegistry.setVerbose(true);
            poD = (FilePathObject) FilePathObject.createDirectories(Paths.get("d:/0temp/D"));
            WatchEvent.Kind[] kind = new WatchEvent.Kind[]{ENTRY_CREATE, ENTRY_MODIFY,ENTRY_DELETE};
            
            mainRegistry.register(Paths.get(poD.getPath()), kind).addListeners( createAdapter())
                    .lock();
            
            if ( poD.getPathObject(".meme.txt") == null ) {
                poD.createData(".meme.txt");
            }
            mainRegistry.processEvents();
            
        } catch (IOException ex) {
            Logger.getLogger(ChainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createRegistryForDButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createRegistryForDButton;
    // End of variables declaration//GEN-END:variables
}
